name: Super-linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Test It Hamed!
        run:
          echo $TEST_ENV_VAR
        env:
          TEST_ENV_VAR: ${{ secrets.TEST_ENV }}